/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pesentación;

import javax.swing.JOptionPane;
import Aplicacion.Calculadora;
import Aplicacion.Iteracion;
import Aplicacion.TMIterador;
import java.awt.Toolkit;
import java.util.ArrayList;

/**
 *
 * @author jonat
 */
public class Booth extends javax.swing.JFrame {

    private TMIterador modelo;

    public Booth() {
        initComponents();
        //Configuración basica de la ventana
        this.setTitle("Algoritmo de Booth");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/Imagenes/icon.png")));
    }

    private static boolean isNumeric(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelMultiplicando = new javax.swing.JLabel();
        jLabelMultiplicador = new javax.swing.JLabel();
        jTextFieldMultiplicando = new javax.swing.JTextField();
        jTextFieldMultiplicador = new javax.swing.JTextField();
        jLabelPrecision = new javax.swing.JLabel();
        jComboPrecision = new javax.swing.JComboBox<>();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonCalcular = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelSigno = new javax.swing.JLabel();
        jLabelBinario = new javax.swing.JLabel();
        jTextResultadoSigno = new javax.swing.JTextField();
        jTextFieldResultadoBinario = new javax.swing.JTextField();
        jLabelResultadoDecimal = new javax.swing.JLabel();
        jTextFieldResultadoDecimal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProcedimientoTabla = new javax.swing.JTable();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        salirPrograma = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algoritmo de Both");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingreso de datos"));

        jLabelMultiplicando.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelMultiplicando.setText("Multiplicando:");

        jLabelMultiplicador.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelMultiplicador.setText("Multiplicador:");

        jTextFieldMultiplicando.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        jTextFieldMultiplicador.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTextFieldMultiplicador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMultiplicadorActionPerformed(evt);
            }
        });

        jLabelPrecision.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelPrecision.setText("Precisión:");

        jComboPrecision.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jComboPrecision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8", "16", "32" }));
        jComboPrecision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboPrecisionActionPerformed(evt);
            }
        });

        jButtonLimpiar.setBackground(new java.awt.Color(102, 102, 102));
        jButtonLimpiar.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/clean-code.png"))); // NOI18N
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonCalcular.setBackground(new java.awt.Color(51, 102, 255));
        jButtonCalcular.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButtonCalcular.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/llaves.png"))); // NOI18N
        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelMultiplicador)
                                .addGap(9, 9, 9)
                                .addComponent(jTextFieldMultiplicador, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelMultiplicando)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMultiplicando)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(jLabelPrecision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboPrecision, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMultiplicando)
                    .addComponent(jTextFieldMultiplicando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPrecision)
                    .addComponent(jComboPrecision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMultiplicador)
                    .addComponent(jTextFieldMultiplicador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpiar)
                    .addComponent(jButtonCalcular))
                .addGap(46, 46, 46))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));

        jLabelSigno.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelSigno.setText("Signo:");

        jLabelBinario.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelBinario.setText("Binario:");

        jTextResultadoSigno.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTextResultadoSigno.setToolTipText("");

        jTextFieldResultadoBinario.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTextFieldResultadoBinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldResultadoBinarioActionPerformed(evt);
            }
        });

        jLabelResultadoDecimal.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabelResultadoDecimal.setText("Decimal:");

        jTextFieldResultadoDecimal.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTextFieldResultadoDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldResultadoDecimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBinario)
                    .addComponent(jLabelResultadoDecimal)
                    .addComponent(jLabelSigno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextResultadoSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldResultadoBinario)
                        .addComponent(jTextFieldResultadoDecimal, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextResultadoSigno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSigno))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBinario)
                    .addComponent(jTextFieldResultadoBinario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelResultadoDecimal)
                    .addComponent(jTextFieldResultadoDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Procedimiento"));

        jTableProcedimientoTabla.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jTableProcedimientoTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Iteración", "Valores", "Bits primarios", "Bits Secundarios", "Bit Adicional"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProcedimientoTabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableProcedimientoTabla.setColumnSelectionAllowed(true);
        jTableProcedimientoTabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableProcedimientoTabla.setShowVerticalLines(true);
        jTableProcedimientoTabla.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(jTableProcedimientoTabla);
        jTableProcedimientoTabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTableProcedimientoTabla.getAccessibleContext().setAccessibleName("");
        jTableProcedimientoTabla.getAccessibleContext().setAccessibleDescription(getTitle());

        jMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        jMenu.setText("Menú");
        jMenu.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/equipo.png"))); // NOI18N
        jMenuItem1.setText("Integrantes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItem1);

        salirPrograma.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        salirPrograma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logout.png"))); // NOI18N
        salirPrograma.setText("Salir");
        salirPrograma.setName("Salir"); // NOI18N
        salirPrograma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirProgramaActionPerformed(evt);
            }
        });
        jMenu.add(salirPrograma);

        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirProgramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirProgramaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirProgramaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Integrantes desarroladores = new Integrantes();
        desarroladores.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextFieldMultiplicadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMultiplicadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMultiplicadorActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextFieldMultiplicando.setText("");
        jTextFieldMultiplicador.setText("");
        jComboPrecision.setSelectedIndex(0);
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        String multiplicando = jTextFieldMultiplicando.getText();
        String multiplicador = jTextFieldMultiplicador.getText();

        if (isNumeric(multiplicando)) {
            if (isNumeric(multiplicador)) {
                Integer valueComboBox = Integer.parseInt(jComboPrecision.getSelectedItem().toString());
                Calculadora calculadoraBoth = new Calculadora();
                ArrayList<String> resultados = calculadoraBoth.procedimiento(multiplicando, multiplicador, valueComboBox);
                ArrayList<Iteracion> tabla = calculadoraBoth.getDatosTabla();
                if (resultados.get(0) != "" && resultados.get(1) != "" && resultados.get(2) != "") {               
                    jTextResultadoSigno.setText(resultados.get(0));
                    jTextFieldResultadoBinario.setText(resultados.get(1));
                    jTextFieldResultadoDecimal.setText(resultados.get(2));
                    modelo = new TMIterador(tabla, valueComboBox);
                    jTableProcedimientoTabla.setModel(modelo);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Verifique si el valor ingresado es valido, este valor debe de ser un número", "Error al ingresar el multiplicador", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Verifique si el valor ingresado es valido, este valor debe de ser un número", "Error al ingresar el multiplicando", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jTextFieldResultadoDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldResultadoDecimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldResultadoDecimalActionPerformed

    private void jTextFieldResultadoBinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldResultadoBinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldResultadoBinarioActionPerformed

    private void jComboPrecisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboPrecisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboPrecisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Booth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Booth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Booth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Booth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JComboBox<String> jComboPrecision;
    private javax.swing.JLabel jLabelBinario;
    private javax.swing.JLabel jLabelMultiplicador;
    private javax.swing.JLabel jLabelMultiplicando;
    private javax.swing.JLabel jLabelPrecision;
    private javax.swing.JLabel jLabelResultadoDecimal;
    private javax.swing.JLabel jLabelSigno;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProcedimientoTabla;
    private javax.swing.JTextField jTextFieldMultiplicador;
    private javax.swing.JTextField jTextFieldMultiplicando;
    private javax.swing.JTextField jTextFieldResultadoBinario;
    private javax.swing.JTextField jTextFieldResultadoDecimal;
    private javax.swing.JTextField jTextResultadoSigno;
    private javax.swing.JMenuItem salirPrograma;
    // End of variables declaration//GEN-END:variables
}
